# Generated by Django 5.1.4 on 2025-06-28 10:33

import django.contrib.auth.models
import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms
import users.utils
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='email')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('bio', models.CharField(blank=True, max_length=255, null=True, verbose_name='bio')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='phone number')),
                ('app_phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[users.utils.validate_phone_number], verbose_name='app phone number')),
                ('telegram_id', models.CharField(max_length=77, unique=True, verbose_name='telegram id')),
                ('language', models.CharField(choices=[('uzbek', 'uzbek'), ('english', 'english'), ('russian', 'russian')], default='uzbek', max_length=20, verbose_name='language')),
                ('role', models.CharField(choices=[('superadmin', 'superadmin'), ('admin', 'admin'), ('simple', 'simple'), ('premium', 'premium'), ('publisher', 'publisher'), ('library', 'library')], default='simple', max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('picture', django_resized.forms.ResizedImageField(crop=None, default='users/pictures/default_user.png', force_format='JPEG', keep_meta=True, quality=85, scale=None, size=[1200, 1200], upload_to='users/pictures/', verbose_name='picture')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('location_text', models.CharField(blank=True, max_length=250, null=True, verbose_name='location text')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.district', verbose_name='district')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.region', verbose_name='region')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otp_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
