# Generated by Django 5.1.4 on 2025-07-09 16:06

import users.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0003_basepost_picture'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_id', None), _negated=True), fields=('telegram_id',), name='unique_telegram_id_if_not_null'),
        ),
    ]
