# Generated by Django 5.1.4 on 2025-06-22 00:59

import authentication.utils
import django.contrib.auth.models
import django.contrib.gis.db.models.fields
import django.utils.timezone
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is superuser')),
                ('is_staff', models.BooleanField(default=False, verbose_name='is staff')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('bio', models.CharField(blank=True, max_length=255, null=True, verbose_name='bio')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='phone number')),
                ('app_phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[authentication.utils.validate_phone_number], verbose_name='phone number')),
                ('telegram_id', models.CharField(max_length=77, unique=True, verbose_name='telegram id')),
                ('language', models.CharField(choices=[('uzbek', 'uzbek'), ('english', 'english'), ('russian', 'russian')], default='uzbek', max_length=20, verbose_name='language')),
                ('role', models.CharField(choices=[('superadmin', 'superadmin'), ('admin', 'admin'), ('simple', 'simple'), ('premium', 'premium'), ('publisher', 'publisher'), ('library', 'library')], default='simple', max_length=20, verbose_name='role')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('picture', django_resized.forms.ResizedImageField(crop=None, default='users/pictures/default_user.png', force_format='JPEG', keep_meta=True, quality=85, scale=None, size=[1200, 1200], upload_to='users/pictures/', verbose_name='picture')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='last name')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('location_text', models.CharField(blank=True, max_length=250, null=True, verbose_name='location text')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp_code', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
