# Generated by Django 5.1.4 on 2025-02-25 19:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('phone_is_visible', models.BooleanField(default=False)),
                ('location_is_visible', models.BooleanField(default=False)),
                ('telegram_id', models.CharField(max_length=77, unique=True)),
                ('role', models.IntegerField(choices=[(1, 'SuperAdmin'), (2, 'Admin'), (3, 'BookShop'), (4, 'SimpleUser')], default=4)),
                ('is_active', models.BooleanField(default=True)),
                ('login_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('otp_code', models.IntegerField(default=0)),
                ('picture', models.ImageField(default='users/pictures/default_user.png', upload_to='users/pictures/')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.district')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.region')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
