# Generated by Django 5.1.4 on 2025-06-25 07:37

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_user_email_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='app_phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[authentication.utils.validate_phone_number], verbose_name='app phone number'),
        ),
    ]
