# Generated by Django 5.1.4 on 2025-06-22 00:59

import django.contrib.gis.db.models.fields
import django.core.validators
import django.db.models.deletion
import django_resized.forms
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('sharing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed'), ('rejected', 'rejected'), ('sold', 'sold')], default='pending', max_length=10, verbose_name='Status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_order', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book_order', to='sharing.book', verbose_name='Book')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.order', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Order item',
                'verbose_name_plural': 'Order items',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('bio', models.CharField(max_length=500, verbose_name='Shop description')),
                ('picture', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=85, scale=None, size=[800, 800], upload_to='shop/pictures', verbose_name='picture')),
                ('star', models.PositiveIntegerField(default=0, verbose_name='Star')),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326)),
                ('location_text', models.TextField(verbose_name='Location text')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone number')),
                ('telegram', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telegram')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='base.district', verbose_name='District')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shops', to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shops', to='base.region', verbose_name='Region')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_order', to='shop.shop', verbose_name='Shop'),
        ),
        migrations.CreateModel(
            name='ShopFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('star', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Star')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='User_feedback', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedbacks',
            },
        ),
        migrations.CreateModel(
            name='ShopStuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stuffs', to='shop.shop', verbose_name='Shop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stuffs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Shop stuff',
                'verbose_name_plural': 'Shop stuffs',
            },
        ),
    ]
