# Generated by Django 5.1.4 on 2025-07-02 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='star',
            field=models.DecimalField(decimal_places=1, max_digits=2, verbose_name='Star'),
        ),
    ]
