# Generated by Django 5.1.4 on 2025-07-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_shop_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='telegram',
            field=models.CharField(blank=True, max_length=77, null=True, verbose_name='Telegram'),
        ),
    ]
