# Generated by Django 5.1.4 on 2025-07-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shop_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='has_post_service',
            field=models.BooleanField(default=False, verbose_name='Has postal service'),
        ),
        migrations.AddField(
            model_name='shop',
            name='instagram',
            field=models.CharField(blank=True, max_length=77, null=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='shop',
            name='lunch',
            field=models.CharField(default='13:00 - 14:00', max_length=50, verbose_name='Lunch'),
        ),
        migrations.AddField(
            model_name='shop',
            name='website',
            field=models.CharField(blank=True, max_length=77, null=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='shop',
            name='working_days',
            field=models.CharField(default='Monday-Saturday', max_length=100, verbose_name='Working days'),
        ),
        migrations.AddField(
            model_name='shop',
            name='working_hours',
            field=models.CharField(default='09:00 - 18:00', max_length=50, verbose_name='Working hours'),
        ),
    ]
