# Generated by Django 5.1.4 on 2025-07-02 10:24

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basepost',
            name='picture',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='JPEG', keep_meta=True, quality=85, scale=None, size=[800, 800], upload_to='base_post/pictures/', verbose_name='Picture'),
            preserve_default=False,
        ),
    ]
