# Generated by Django 5.1.4 on 2025-06-28 10:33

import django_ckeditor_5.fields
import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('picture', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=85, scale=None, size=[800, 800], upload_to='books/pictures/', verbose_name='picture')),
                ('owner_type', models.CharField(choices=[('user', 'user'), ('shop', 'shop')], default='user', max_length=4, verbose_name='owner type')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('language', models.CharField(max_length=55, verbose_name='language')),
                ('script_type', models.CharField(blank=True, max_length=30, null=True, verbose_name='script type')),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='description')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('cover_type', models.CharField(choices=[('hard', 'hard'), ('soft', 'soft')], max_length=4, verbose_name='cover type')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='discount price')),
                ('pages', models.PositiveIntegerField(verbose_name='pages number')),
                ('publication_year', models.PositiveIntegerField(verbose_name='publication year')),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, verbose_name='isbn')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_banned', models.BooleanField(default=False, verbose_name='is banned')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='BookComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(max_length=777, verbose_name='comment')),
                ('is_banned', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'BookComment',
                'verbose_name_plural': 'BookComments',
            },
        ),
        migrations.CreateModel(
            name='BookCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BookCommentLike',
                'verbose_name_plural': 'BookCommentLikes',
            },
        ),
        migrations.CreateModel(
            name='BookLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BookLike',
                'verbose_name_plural': 'BookLikes',
            },
        ),
        migrations.CreateModel(
            name='BookView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BookView',
                'verbose_name_plural': 'BookViews',
            },
        ),
    ]
