# Generated by Django 5.1.4 on 2025-04-19 00:54

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
