# Generated by Django 5.1.4 on 2025-07-02 00:01

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tag name')),
                ('picture', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to='books/tags', verbose_name='tag picture')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='exchange_book',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Exchange book'),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(choices=[('gift', 'gift'), ('exchange', 'exchange'), ('seller', 'seller')], default='gift', max_length=10, verbose_name='book type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price'),
        ),
        migrations.AddField(
            model_name='book',
            name='tag',
            field=models.ManyToManyField(related_name='books', to='sharing.tag', verbose_name='Tag'),
        ),
    ]
