# Generated by Django 5.1.4 on 2025-08-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0005_subcategory_book_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='for_home_page',
            field=models.BooleanField(default=False, verbose_name='for home page'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_used',
            field=models.BooleanField(default=False, verbose_name='is new'),
        ),
    ]
